name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to Tomcat Server
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
            echo "$SSH_KEY" > key.pem
            chmod 600 key.pem
  
            FILE=github-action-maven-tutorial-1.0-SNAPSHOT-jar-with-dependencies.jar

            echo "Uploading $FILE to EC2"
            scp -i key.pem -o StrictHostKeyChecking=no target/$FILE $EC2_USER@$EC2_HOST:~/app.jar

            echo "Restarting app on EC2"
            ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            echo "Killing old Java app (if any)..."
            pkill -f 'java -jar app.jar' || true

            echo "Starting new app..."
            nohup java -jar app.jar > app.log 2>&1 &

            echo "App started. Check app.log for logs."
            EOF
