name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy WAR to Tomcat Server
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem

          echo "Listing current and target directories:"
          ls -la ./
          ls -la target/

          # Try to find WAR in current directory first, then in target/
          FILE=$(ls *.war 2>/dev/null | head -n 1 || true)

          if [ -z "$FILE" ]; then
            FILE=$(ls target/*.war 2>/dev/null | head -n 1 || true)
          fi

          if [ -z "$FILE" ]; then
            echo "ERROR: No WAR file found!"
            exit 1
          fi

          echo "Uploading WAR file: $FILE"
          scp -i key.pem -o StrictHostKeyChecking=no "$FILE" $EC2_USER@$EC2_HOST:/home/$EC2_USER/app.war

          echo "Moving WAR file and restarting Tomcat on EC2"
          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            sudo mv /home/$EC2_USER/app.war /opt/tomcat/webapps/app.war
            sudo systemctl restart tomcat
          EOF
